export const Dnd = imports.ui.dnd;
export const Main = imports.ui.main;
export const Volume = imports.ui.status.volume;
export const HotCorner = imports.ui.layout.HotCorner;
export const Keyboard = imports.ui.status.keyboard
export const SwitcherPopup = imports.ui.switcherPopup;
export const { WorkspaceSwitcherPopup } = imports.ui.workspaceSwitcherPopup;
export const { AppMenu } = imports.ui.appMenu;
export const { PopupSubMenuMenuItem, PopupSeparatorMenuItem, PopupBaseMenuItem, PopupMenuSection, Ornament } = imports.ui.popupMenu;
export const ArrowIcon = imports.ui.popupMenu.arrowIcon;
export const AppFavorites = imports.ui.appFavorites;
export const { Slider } = imports.ui.slider;
