#!/bin/bash

cd ./extension

gnome-extensions pack --force\
                      --podir=locale ./\
                      --extra-source ../LICENSE\
                      --extra-source ui/\
                      --extra-source utils/\
                      --extra-source shell/\
                      --extra-source settings/\
                      --out-dir ../