#!/bin/bash

Path=~/.local/share/gnome-shell/extensions/`cat ./metadata.json | grep -oP '(?<="uuid": ")[^"]*'`

mkdir -p $Path

glib-compile-schemas ./schemas/

\cp extension.js taskbar.js metadata.json $Path
\cp -r ./schemas $Path