/**
 * @enum {string}
 */
export const SettingsPath = {
    Panel: 'panel',
    Taskbar: 'taskbar',
    NotificationCounter: 'notification-counter'
};

/**
 * @enum {string}
 */
export const SettingsKey = {
    Modules: 'modules',
    LauncherApi: 'launcher-api',
    NotificationsLauncherApi: 'notifications-launcher-api',
    NotificationsCountAttentionSources: 'notifications-count-attention-sources',
    Items: 'items',
    SoundVolumeControl: 'sound-volume-control',
    ClickToHideOverview: 'click-to-hide-overview',
    ShowFavorites: 'show-favorites',
    IsolateWorkspaces: 'isolate-workspaces',
    ShowAllWindows: 'show-all-windows',
    Separator: 'separator',
    WindowRouting: 'window-routing',
    WindowRoutnigWatchdog: 'window-routing-watchdog',
    PreferredMonitor: 'preferred-monitor',
    AttentionBehavior: 'attention-behavior',
    AttentionNotificationsBehavior: 'attention-notifications-behavior',
    AppButtonMenus: 'appbutton-menus',
    AppButtonTooltips: 'appbutton-tooltips',
    AppButtonIndicators: 'appbutton-indicators',
    AppButtonNotificationBadges: 'appbutton-notification-badges',
    AppButtonProgressBars: 'appbutton-progress-bars',
    AppButtonSoundVolumeControl: 'appbutton-sound-volume-control',
    AppButtonDragAndDrop: 'appbutton-drag-and-drop',
    AppButtonScroll: 'appbutton-scroll',
    AppButtonIconSize: 'appbutton-icon-size',
    AppButtonIconPath: '~appbutton-icon-path',
    AppButtonIconHPadding: 'appbutton-icon-hpadding',
    AppButtonIconVPadding: 'appbutton-icon-vpadding',
    AppButtonSpacing: 'appbutton-spacing',
    AppButtonRoundness: 'appbutton-roundness',
    AppButtonBacklightColor: 'appbutton-backlight-color',
    AppButtonBacklightDominantColor: 'appbutton-backlight-dominant-color',
    AppButtonBacklightIntensity: 'appbutton-backlight-intensity',
    AppButtonActivateBehavior: 'appbutton-activate-behavior',
    AppButtonMinimizeAction: 'appbutton-minimize-action',
    AppButtonConfigOverride: 'appbutton-config-override',
    IndicatorDominantColorActive: 'indicator-dominant-color-active',
    IndicatorColorActive: 'indicator-color-active',
    IndicatorDominantColorInactive: 'indicator-dominant-color-inactive',
    IndicatorColorInactive: 'indicator-color-inactive',
    IndicatorPosition: 'indicator-position',
    IndicatorSizeInactive: 'indicator-size-inactive',
    IndicatorSizeActive: 'indicator-size-active',
    IndicatorWeightInactive: 'indicator-weight-inactive',
    IndicatorWeightActive: 'indicator-weight-active',
    IndicatorSpacingInactive: 'indicator-spacing-inactive',
    IndicatorSpacingActive: 'indicator-spacing-active',
    IndicatorOffsetInactive: 'indicator-offset-inactive',
    IndicatorOffsetActive: 'indicator-offset-active',
    IndicatorLimitInactive: 'indicator-limit-inactive',
    IndicatorLimitActive: 'indicator-limit-active',
    NotificationBadgeColor: 'notification-badge-color',
    NotificationBadgeFontColor: 'notification-badge-font-color',
    NotificationBadgeBorderColor: 'notification-badge-border-color',
    NotificationBadgePosition: 'notification-badge-position',
    NotificationBadgeSize: 'notification-badge-size',
    NotificationBadgeRoundness: 'notification-badge-roundness',
    NotificationBadgeOffset: 'notification-badge-offset',
    NotificationBadgeMaxCount: 'notification-badge-max-count',
    TooltipShowDelay: 'tooltip-show-delay',
    TooltipHideDelay: 'tooltip-hide-delay',
    TooltipShrinkWindowTitles: 'tooltip-shrink-window-titles',
    TooltipWindowPreviews: 'tooltip-window-previews',
    ProgressBarPosition: 'progress-bar-position',
    ProgressBarWidth: 'progress-bar-width',
    ProgressBarHeight: 'progress-bar-height',
    ProgressBarOffset: 'progress-bar-offset',
    ProgressBarBackgroundColor: 'progress-bar-background-color',
    ProgressBarFillColor: 'progress-bar-fill-color',
    HideEhenEmpty: 'hide-when-empty',
    CenterClockPosition: 'center-clock-position',
    MaxCount: 'max-count',
    FontSize: 'font-size',
    Roundness: 'roundness',
    VerticalOffset: 'vertical-offset',
    ColorWhenEmpty: 'color-when-empty',
    ColorWhenNotEmpty: 'color-when-not-empty',
    ColorWhenEmptyDnd: 'color-when-empty-dnd',
    ColorWhenNotEmptyDnd: 'color-when-not-empty-dnd',
    TextColor: 'text-color',
    TextColorDnd: 'text-color-dnd',
    ColorsDnd: 'colors-dnd'
};
