#!/bin/sh

if [ "$1" = "dev" ]; then

    cd ../extension-dev

    gnome-extensions pack --force\
                        --extra-source devUtils.js/\
                        --extra-source ../LICENSE\
                        --extra-source ../extension/schemas/\
                        --extra-source ../extension/assets/\
                        --extra-source ../extension/ui/\
                        --extra-source ../extension/services/\
                        --extra-source ../extension/utils/\
                        --extra-source ../extension/core/\
                        --extra-source ../extension/tweaks/\
                        --extra-source ../extension/settings/\
                        --extra-source ../extension/stylesheet.css/\
                        --out-dir ../

    exit 0
fi

cd ../extension

gnome-extensions pack --force\
                      --podir=locale ./\
                      --extra-source ../LICENSE\
                      --extra-source assets/\
                      --extra-source ui/\
                      --extra-source services/\
                      --extra-source utils/\
                      --extra-source core/\
                      --extra-source tweaks/\
                      --extra-source settings/\
                      --out-dir ../
