#!/bin/sh

if [ "$1" = "dev" ]; then

    cd ../extension-dev

    gnome-extensions pack --force\
                          --extra-source devUtils.js/\
                          --extra-source ../extension/prefs.js/\
                          --extra-source ../extension/schemas/\
                          --extra-source ../extension/assets/\
                          --extra-source ../extension/main/\
                          --extra-source ../extension/preferences/\
                          --extra-source ../extension/services/\
                          --extra-source ../extension/ui/\
                          --extra-source ../extension/tweaks/\
                          --extra-source ../extension/utils/\
                          --extra-source ../extension/shared/\
                          --extra-source ../extension/stylesheet.css/\
                          --extra-source ../LICENSE\
                          --out-dir ../

    exit 0
fi

cd ../extension

gnome-extensions pack --force\
                      --podir=locale ./\
                      --extra-source assets/\
                      --extra-source main/\
                      --extra-source preferences/\
                      --extra-source services/\
                      --extra-source ui/\
                      --extra-source tweaks/\
                      --extra-source utils/\
                      --extra-source shared/\
                      --extra-source ../LICENSE\
                      --out-dir ../
