#!/bin/sh

if [ "$1" = "dev" ]; then

    cd ../extension-dev
    cp -r ../extension/locale ./locale

    gnome-extensions pack --force\
                          --podir=locale ./\
                          --extra-source devUtils.js/\
                          --extra-source ../extension/prefs.js/\
                          --extra-source ../extension/schemas/\
                          --extra-source ../extension/assets/\
                          --extra-source ../extension/main/\
                          --extra-source ../extension/preferences/\
                          --extra-source ../extension/shared/\
                          --extra-source ../extension/stylesheet.css/\
                          --extra-source ../LICENSE\
                          --out-dir ../
    rm -rf ./locale
    exit 0
fi

cd ../extension

gnome-extensions pack --force\
                      --podir=locale ./\
                      --extra-source assets/\
                      --extra-source main/\
                      --extra-source preferences/\
                      --extra-source shared/\
                      --extra-source ../LICENSE\
                      --out-dir ../
