#!/bin/sh

cd ../extension

POT_FILE_NAME=`cat ./metadata.json | grep -oP '(?<="gettext-domain": ")[^"]*'`

find ./preferences/ui/ -name '*.ui' > POT_FILES
echo ./shared/enums/labels.js >> POT_FILES

xgettext --files-from=POT_FILES --output=./locale/$POT_FILE_NAME.pot

rm POT_FILES
