#!/bin/sh

cd ../

echo '# TSCHECK'
echo ''
tsc_output=$(npx -p typescript tsc --noEmit -p jsconfig.json 2>&1)
echo "$tsc_output" | grep -E '^(extension/|extension-dev/)' || true
echo ''
echo '# ESLINT'
echo ''
npx eslint . --max-warnings 0
